// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_backend.Migrations;

#nullable disable

namespace taskbackend.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("task_backend.Models.task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.ToTable("task");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Title = "greeting",
                            completed = false
                        },
                        new
                        {
                            TaskId = 2,
                            Title = "go to school",
                            completed = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
